default: true
MD013: false  # Line length
MD033: false  # Allow inline HTML
MD025: false  # Multiple top-level headings
MD026: false  # Trailing punctuation in heading
MD041: false  # First line heading
