fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.8.0
        args:
          - -l 79
        verbose: true
        entry: bash -c 'blacken-docs "$@" || true' --
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.8
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--no-hashes", "--output-file=requirements.txt"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.83.2
    hooks:
      - id: cfn-python-lint
        files: ^cloudformation/.*\.(json|ya?ml)$      # Only check files in cloudformation directory
        # Alternatively, you could use a pattern that matches common CloudFormation template names:
        # files: (template|stack|cfn).*\.(json|ya?ml)$
        exclude: |
          (?x)(
            ^.pre-commit-config/.*\.ya?ml$|
            ^.terraform-docs.ya?ml$|
            ^\.tflint.hcl$
          )

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.1.56
    hooks:
      - id: checkov
        args: [--quiet, --skip-path, themes]
        files: ^terraform/.*$
