name: PR Checks
on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Markdown Lint
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: "src/content/**/*.md"

      # Hugo Build
      - name: Build Hugo Site
        working-directory: ./src
        run: hugo --minify

      # HTML Check
      - name: Test HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./src/public"
          arguments: --check-html --check-img-http --check-opengraph --check-sri --check-external-hash --check-favicon
        continue-on-error: true  # HTML checks can be strict, might want to make this advisory

      # Optional: Add a comment to PR with results
      - name: PR Comment
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const output = `#### PR Check Results
            - ✅ Markdown Lint
            - ✅ Hugo Build
            - ✅ HTML Check
            
            *Automated check completed at ${new Date().toUTCString()}*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })